raw = input("请输入一个英文句子（单词用空格隔开）：")
sentence = raw.strip()
print(f"句子长度:{len(sentence)}")
print(f"清洗后内容:{sentence}")
words = sentence.split()
print(f"单词列表:{words}")
print(f"一共{len(words)}个单词")
print(f"第一个单词{words[0]}")
print(f"第一个单词的首字母{words[0][0]}")
print(f"最后三个字符：{sentence[-3:]}")
print(f"把‘o’换成‘0’：{sentence.replace('o','0')}")