raw = input("请输入日期（格式 年-月-日）：")
cleaned = raw.replace('-','')
print(f"去掉横线后:{cleaned}")
print(f"长度：{len(cleaned)}")
group = raw.split('-')
print(f"年份：{group[0]}")
print(f"月份：{group[1]}")
print(f"日：{group[2]}")
print(f"中文格式:{group[0]}年{group[1]}月{group[2]}日")
print(f"拆分结果：{group}")
print(f"斜杠格式:{group[0]}/{group[1]}/{group[2]}")